/-
Copyright (c) 2026 The Zhong formalisation contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zhong formalisation contributors
-/
import Zhong.ClosedWalk

/-!
# The closed-walk group and the alternating group (towards the converse of Proposition 3)

This file collects the first steps of the converse direction of Proposition 3 of
Zhong (2023): the closed-walk group `closedGroup p` at a cell `p` should be exactly
the group of even cell permutations fixing `p`.

* `closedGroup_le_stabilizer` : every closed-walk permutation fixes its base point.
* `altOn U` : the alternating group on a finite set `U`, viewed as permutations of the
  ambient board.
* `alt_fin5` : `A₅` is generated by the two three-cycles `(0 1 2)` and `(0 3 4)`.
* `alt_five_le` : the *five-point lemma*.  If a subgroup contains two three-cycles on
  five points sharing one point, it contains the alternating group on those five points.

The remaining steps towards the converse (gluing these five-point groups along the grid
and deducing `A_X ≤ closedGroup p`) are not yet formalised.
-/

namespace Zhong

open Equiv

variable {n m : ℕ}

/-- Every element of the closed-walk group at `p` fixes `p`. -/
theorem closedGroup_le_stabilizer (p : Cell n m) :
    closedGroup p ≤ MulAction.stabilizer (Equiv.Perm (Cell n m)) p := by
  rw [closedGroup, Subgroup.closure_le]
  rintro g ⟨σ, hσ, rfl⟩
  change permOf p σ ∈ MulAction.stabilizer (Equiv.Perm (Cell n m)) p
  rw [MulAction.mem_stabilizer_iff]
  change permOf p σ p = p
  have hfix : (permOf p σ).symm p = p := by rw [permOf_symm_apply, hσ]
  calc permOf p σ p = permOf p σ ((permOf p σ).symm p) := by rw [hfix]
    _ = p := Equiv.apply_symm_apply _ _


/-- Every element of the closed-walk group at `p` fixes `p`. -/
theorem closedGroup_apply_self {p : Cell n m} {g : Equiv.Perm (Cell n m)}
    (hg : g ∈ closedGroup p) : g p = p :=
  closedGroup_le_stabilizer p hg

/-! ### The five-point lemma -/

section FivePoint

set_option maxHeartbeats 1600000
set_option linter.style.haveILetI false

variable {X : Type*} [Fintype X] [DecidableEq X]

/-- The alternating group on a finite set `U`, viewed as permutations of `X`. -/
noncomputable def altOn (U : Finset X) : Subgroup (Equiv.Perm X) :=
  (alternatingGroup ↥U).map (Equiv.Perm.ofSubtype (p := (· ∈ U)))

/-- `altOn` is monotone in the underlying finite set. -/
theorem altOn_mono {U V : Finset X} (hUV : U ⊆ V) : altOn U ≤ altOn V := by
  intro g hg
  rw [altOn, Subgroup.mem_map] at hg
  obtain ⟨σ, hσ, rfl⟩ := hg
  rw [altOn, Subgroup.mem_map]
  have hsupp : ((Equiv.Perm.ofSubtype (p := (· ∈ U)) σ).support : Set X) ⊆ (V : Set X) := by
    intro x hx
    rw [Finset.mem_coe, Equiv.Perm.mem_support_ofSubtype] at hx
    exact Finset.mem_coe.mpr (hUV hx.1)
  have hmem : Equiv.Perm.ofSubtype (p := (· ∈ U)) σ ∈
      (Equiv.Perm.ofSubtype (p := (· ∈ V))).range :=
    Equiv.Perm.mem_range_ofSubtype_iff.mpr hsupp
  obtain ⟨τ, hτ⟩ := hmem
  refine ⟨τ, ?_, hτ⟩
  rw [Equiv.Perm.mem_alternatingGroup]
  rw [← Equiv.Perm.sign_ofSubtype (p := (· ∈ V)) τ, hτ,
    Equiv.Perm.sign_ofSubtype (p := (· ∈ U)) σ]
  exact hσ

/-- An element of `altOn U` is supported in `U`. -/
theorem support_of_mem_altOn {U : Finset X} {g : Equiv.Perm X} (hg : g ∈ altOn U) :
    g.support ⊆ U := by
  rw [altOn, Subgroup.mem_map] at hg
  obtain ⟨σ, -, rfl⟩ := hg
  intro x hx
  rw [Equiv.Perm.mem_support_ofSubtype] at hx
  exact hx.1

/-- An element of `altOn U` fixes the complement of `U`. -/
theorem apply_eq_self_of_mem_altOn {U : Finset X} {g : Equiv.Perm X} (hg : g ∈ altOn U)
    {x : X} (hx : x ∉ U) : g x = x := by
  by_contra h
  exact hx (support_of_mem_altOn hg (Equiv.Perm.mem_support.mpr h))

/-- An even permutation fixing the complement of `U` lies in `altOn U`. -/
theorem mem_altOn_of_fixes_compl {U : Finset X} {g : Equiv.Perm X}
    (hfix : ∀ x, x ∉ U → g x = x) (hsign : Equiv.Perm.sign g = 1) : g ∈ altOn U := by
  have hsupp : (g.support : Set X) ⊆ (U : Set X) := by
    intro x hx
    by_contra hxU
    rw [Finset.mem_coe, Equiv.Perm.mem_support] at hx
    exact hx (hfix x (by simpa using hxU))
  have hmem : g ∈ (Equiv.Perm.ofSubtype (p := (· ∈ U))).range :=
    Equiv.Perm.mem_range_ofSubtype_iff.mpr hsupp
  obtain ⟨τ, hτ⟩ := hmem
  rw [altOn, Subgroup.mem_map]
  refine ⟨τ, ?_, hτ⟩
  rw [Equiv.Perm.mem_alternatingGroup]
  rw [← Equiv.Perm.sign_ofSubtype (p := (· ∈ U)) τ, hτ, hsign]

/-- An element of `altOn U` is even. -/
theorem sign_eq_one_of_mem_altOn {U : Finset X} {g : Equiv.Perm X} (hg : g ∈ altOn U) :
    Equiv.Perm.sign g = 1 := by
  rw [altOn, Subgroup.mem_map] at hg
  obtain ⟨σ, hσ, rfl⟩ := hg
  rw [Equiv.Perm.sign_ofSubtype]
  exact hσ

/-- Conjugation by a permutation sends `altOn U` to `altOn (U.map u)`. -/
theorem conj_mem_altOn {U : Finset X} (u : Equiv.Perm X) {g : Equiv.Perm X}
    (hg : g ∈ altOn U) : u * g * u⁻¹ ∈ altOn (U.map u.toEmbedding) := by
  apply mem_altOn_of_fixes_compl
  · intro x hx
    have hx' : u⁻¹ x ∉ U := by
      intro h
      exact hx (Finset.mem_map.mpr ⟨u⁻¹ x, h, by simp⟩)
    change u (g (u⁻¹ x)) = x
    rw [apply_eq_self_of_mem_altOn hg hx']
    exact Equiv.apply_symm_apply u x
  · rw [map_mul, map_mul, map_inv, sign_eq_one_of_mem_altOn hg]
    simp

/-- `A₅` is generated by the three-cycles `(0 1 2)` and `(0 3 4)`. -/
theorem alt_fin5 : alternatingGroup (Fin 5) ≤
    Subgroup.closure ({Equiv.swap (0:Fin 5) 1 * Equiv.swap 1 2,
                       Equiv.swap (0:Fin 5) 3 * Equiv.swap 3 4} : Set (Equiv.Perm (Fin 5))) := by
  let τ : Equiv.Perm (Fin 5) := Equiv.swap 0 1 * Equiv.swap 1 2
  let σ : Equiv.Perm (Fin 5) := Equiv.swap 0 3 * Equiv.swap 3 4
  let G : Subgroup (Equiv.Perm (Fin 5)) := Subgroup.closure {τ, σ}
  have hτ : τ ∈ G := Subgroup.subset_closure (by simp)
  have hσ : σ ∈ G := Subgroup.subset_closure (by simp)
  have h3 : Equiv.Perm.IsThreeCycle τ := by
    dsimp only [τ]
    rw [Equiv.swap_comm (0:Fin 5) 1]
    exact Equiv.Perm.isThreeCycle_swap_mul_swap_same (show (1:Fin 5) ≠ 0 by decide)
      (show (1:Fin 5) ≠ 2 by decide) (show (0:Fin 5) ≠ 2 by decide)
  have hall : ∀ x y : Fin 5, ∃ k : Fin 5, ((τ * σ) ^ (k : ℕ)) x = y := by decide
  have hcyc : ∀ x y : Fin 5, ∃ g : G, g • x = y := by
    intro x y
    obtain ⟨k, hk⟩ := hall x y
    exact ⟨⟨(τ * σ) ^ (k : ℕ), G.pow_mem (G.mul_mem hτ hσ) _⟩, hk⟩
  haveI : MulAction.IsPretransitive G (Fin 5) := ⟨hcyc⟩
  exact Equiv.Perm.alternatingGroup_le_of_isPreprimitive_of_isThreeCycle_mem
    (MulAction.IsPreprimitive.of_prime_card (by norm_num : Nat.Prime (Nat.card (Fin 5))))
    h3 hτ

omit [Fintype X] in
/-- `ofSubtype (e.permCongr p)` acts as `e ∘ p ∘ e⁻¹` on the range of `e`. -/
theorem ofSubtype_permCongr_apply {U : Finset X} (e : Fin 5 ≃ ↥U) (p : Equiv.Perm (Fin 5))
    (i : Fin 5) :
    Equiv.Perm.ofSubtype (p := (· ∈ U)) (e.permCongr p) (e i) = e (p i) := by
  rw [Equiv.Perm.ofSubtype_apply_of_mem _ (e i).2, Equiv.permCongr_apply, Equiv.symm_apply_apply]

omit [Fintype X] in
/-- **Five-point lemma.**  If a subgroup `G ≤ Perm X` contains the two three-cycles on the
five points `v 0, …, v 4` sharing `v 0`, then it contains the alternating group on those
five points. -/
theorem alt_five_le {v : Fin 5 → X} (hv : Function.Injective v)
    {G : Subgroup (Equiv.Perm X)}
    (h1 : Equiv.swap (v 0) (v 1) * Equiv.swap (v 1) (v 2) ∈ G)
    (h2 : Equiv.swap (v 0) (v 3) * Equiv.swap (v 3) (v 4) ∈ G) :
    altOn (Finset.univ.image v) ≤ G := by
  let U : Finset X := Finset.univ.image v
  let τ5 : Equiv.Perm (Fin 5) := Equiv.swap 0 1 * Equiv.swap 1 2
  let σ5 : Equiv.Perm (Fin 5) := Equiv.swap 0 3 * Equiv.swap 3 4
  let f : Fin 5 → ↥U := fun i => ⟨v i, Finset.mem_image.mpr ⟨i, Finset.mem_univ i, rfl⟩⟩
  have hf : Function.Bijective f := by
    constructor
    · intro i j hij; exact hv (Subtype.ext_iff.mp hij)
    · intro x
      obtain ⟨i, _, hi⟩ := Finset.mem_image.mp x.2
      exact ⟨i, Subtype.ext hi⟩
  let e : Fin 5 ≃ ↥U := Equiv.ofBijective f hf
  have he : ∀ i, e i = f i := fun i => Equiv.ofBijective_apply _ _ _
  have hL : (alternatingGroup (Fin 5)).map e.permCongrHom.toMonoidHom = alternatingGroup ↥U := by
    ext g
    rw [Subgroup.mem_map_equiv, Equiv.permCongrHom_symm]
    simp only [Equiv.permCongrHom_coe, Equiv.Perm.mem_alternatingGroup, Equiv.Perm.sign_permCongr]
  have hR : (Subgroup.closure ({τ5, σ5} : Set (Equiv.Perm (Fin 5)))).map e.permCongrHom.toMonoidHom
      = Subgroup.closure {e.permCongr τ5, e.permCongr σ5} := by
    rw [MonoidHom.map_closure, Set.image_pair]
    congr 1
  have hmap : alternatingGroup ↥U ≤ Subgroup.closure {e.permCongr τ5, e.permCongr σ5} := by
    rw [← hL, ← hR]
    exact Subgroup.map_mono (f := e.permCongrHom.toMonoidHom) alt_fin5
  have hid1 : Equiv.Perm.ofSubtype (p := (· ∈ U)) (e.permCongr τ5)
      = Equiv.swap (v 0) (v 1) * Equiv.swap (v 1) (v 2) := by
    dsimp only [τ5]
    ext x
    by_cases hx : x ∈ U
    · obtain ⟨i, _, rfl⟩ := Finset.mem_image.mp hx
      have hvi : (e i : X) = v i := by rw [he i]
      rw [← hvi, ofSubtype_permCongr_apply]
      fin_cases i <;>
        simp [he, f, Equiv.swap_apply_def, hv.eq_iff]
    · rw [Equiv.Perm.ofSubtype_apply_of_not_mem _ hx]
      symm
      have h0 : x ≠ v 0 := fun h => hx (h ▸ Finset.mem_image.mpr ⟨0, Finset.mem_univ 0, rfl⟩)
      have h1 : x ≠ v 1 := fun h => hx (h ▸ Finset.mem_image.mpr ⟨1, Finset.mem_univ 1, rfl⟩)
      have h2 : x ≠ v 2 := fun h => hx (h ▸ Finset.mem_image.mpr ⟨2, Finset.mem_univ 2, rfl⟩)
      simp [Equiv.swap_apply_def, h0, h1, h2]
  have hid2 : Equiv.Perm.ofSubtype (p := (· ∈ U)) (e.permCongr σ5)
      = Equiv.swap (v 0) (v 3) * Equiv.swap (v 3) (v 4) := by
    dsimp only [σ5]
    ext x
    by_cases hx : x ∈ U
    · obtain ⟨i, _, rfl⟩ := Finset.mem_image.mp hx
      have hvi : (e i : X) = v i := by rw [he i]
      rw [← hvi, ofSubtype_permCongr_apply]
      fin_cases i <;>
        simp [he, f, Equiv.swap_apply_def, hv.eq_iff]
    · rw [Equiv.Perm.ofSubtype_apply_of_not_mem _ hx]
      symm
      have h0 : x ≠ v 0 := fun h => hx (h ▸ Finset.mem_image.mpr ⟨0, Finset.mem_univ 0, rfl⟩)
      have h3 : x ≠ v 3 := fun h => hx (h ▸ Finset.mem_image.mpr ⟨3, Finset.mem_univ 3, rfl⟩)
      have h4 : x ≠ v 4 := fun h => hx (h ▸ Finset.mem_image.mpr ⟨4, Finset.mem_univ 4, rfl⟩)
      simp [Equiv.swap_apply_def, h0, h3, h4]
  have hmem1 : e.permCongr τ5 ∈ G.comap (Equiv.Perm.ofSubtype (p := (· ∈ U))) := by
    rw [Subgroup.mem_comap, hid1]; exact h1
  have hmem2 : e.permCongr σ5 ∈ G.comap (Equiv.Perm.ofSubtype (p := (· ∈ U))) := by
    rw [Subgroup.mem_comap, hid2]; exact h2
  have hclosure : Subgroup.closure {e.permCongr τ5, e.permCongr σ5}
      ≤ G.comap (Equiv.Perm.ofSubtype (p := (· ∈ U))) := by
    rw [Subgroup.closure_le]
    rintro x (rfl | rfl)
    · exact hmem1
    · exact hmem2
  rw [altOn]
  let os := Equiv.Perm.ofSubtype (p := (· ∈ U))
  exact le_trans (Subgroup.map_mono (f := os) (hmap.trans hclosure))
    (Subgroup.map_comap_le (f := os) G)

end FivePoint

end Zhong
